// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBceyovVMjfUseX5B05Ys9rXLLoYRaMoOk',
    appId: '1:404770600917:web:3f6259817b664ec4382f5c',
    messagingSenderId: '404770600917',
    projectId: 'my-project-de-entrega',
    authDomain: 'my-project-de-entrega.firebaseapp.com',
    storageBucket: 'my-project-de-entrega.firebasestorage.app',
    measurementId: 'G-XWW7EY9LBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZPk6JfiiXqNHS-ND5VWRq5wM39djf9eU',
    appId: '1:404770600917:android:ac60c59e5223bb70382f5c',
    messagingSenderId: '404770600917',
    projectId: 'my-project-de-entrega',
    storageBucket: 'my-project-de-entrega.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1f04wILS8vxMTbtB2M77YuYDe_qa_2HI',
    appId: '1:404770600917:ios:09976a84a2abab67382f5c',
    messagingSenderId: '404770600917',
    projectId: 'my-project-de-entrega',
    storageBucket: 'my-project-de-entrega.firebasestorage.app',
    iosBundleId: 'com.example.procafes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1f04wILS8vxMTbtB2M77YuYDe_qa_2HI',
    appId: '1:404770600917:ios:09976a84a2abab67382f5c',
    messagingSenderId: '404770600917',
    projectId: 'my-project-de-entrega',
    storageBucket: 'my-project-de-entrega.firebasestorage.app',
    iosBundleId: 'com.example.procafes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBceyovVMjfUseX5B05Ys9rXLLoYRaMoOk',
    appId: '1:404770600917:web:7eb25c3e00744526382f5c',
    messagingSenderId: '404770600917',
    projectId: 'my-project-de-entrega',
    authDomain: 'my-project-de-entrega.firebaseapp.com',
    storageBucket: 'my-project-de-entrega.firebasestorage.app',
    measurementId: 'G-30962LQF99',
  );
}
